force-app/main/default/objects/Product2/fields/PricePerUnit__c.field-meta.xml
<CustomField>
    <fullName>PricePerUnit__c</fullName>
    <label>Price Per Unit</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/QuantityAvailable__c.field-meta.xml
<CustomField>
    <fullName>QuantityAvailable__c</fullName>
    <label>Quantity Available</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/selector/ProductSelector.cls
public with sharing class ProductSelector implements ProductISelector {
  private static Dependency impl = new Dependency(
    ProductSelector.class
  );

  public static ProductISelector newInstance() {
    return (ProductISelector) impl.newInstance();
  }

  public List<Product2> getAllAvailableProducts() {
    return [
      SELECT
        Id,
        Name,
        ProductCode,
        Description,
        PricePerUnit__c,
        QuantityAvailable__c
      FROM Product2
      WHERE QuantityAvailable__c > 0
    ];
  }

  public List<Product2> selectByIds(List<Id> ids) {
    return [
      SELECT
        Id,
        Name,
        ProductCode,
        Description,
        PricePerUnit__c,
        QuantityAvailable__c
      FROM Product2
      WHERE Id IN :ids
    ];
  }
}