force-app/main/default/objects/Product2/fields/PricePerUnit__c.field-meta.xml
<CustomField>
    <fullName>PricePerUnit__c</fullName>
    <label>Price Per Unit</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/QuantityAvailable__c.field-meta.xml
<CustomField>
    <fullName>QuantityAvailable__c</fullName>
    <label>Quantity Available</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PurchaseOrder__c/PurchaseOrder__c.object-meta.xml
<CustomObject>
    <label>PurchaseOrder</label>
    <nameField>
        <displayFormat>OrderNumber #{0000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PurchaseOrders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PurchaseOrder__c/fields/OrderPrice__c.field-meta.xml
<CustomField>
    <fullName>OrderPrice__c</fullName>
    <label>Order Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PurchaseOrder__c/fields/OrderStatus__c.field-meta.xml
<CustomField>
    <fullName>OrderStatus__c</fullName>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PurchaseOrderLineItems__c/PurchaseOrderLineItems__c.object-meta.xml
<CustomObject>
    <label>PurchaseOrderLineItem</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Line Item For Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PurchaseOrderLineItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PurchaseOrderLineItems__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>PurchaseOrderLineItems</relationshipLabel>
    <relationshipName>PurchaseOrderLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PurchaseOrderLineItems__c/fields/PurchaseOrder__c.field-meta.xml
<CustomField>
    <fullName>PurchaseOrder__c</fullName>
    <label>PurchaseOrder</label>
    <referenceTo>PurchaseOrder__c</referenceTo>
    <relationshipLabel>PurchaseOrderLineItems</relationshipLabel>
    <relationshipName>PurchaseOrderLineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ShoppingCartController.cls
public with sharing class ShoppingCartController {
  @AuraEnabled(cacheable=true)
  public static List<Product2> getProducts() {
    return ProductSelector.newInstance().getAllAvailableProducts();
  }

  @AuraEnabled
  public static Id placeOrder(Map<Id, Integer> cartMap) {
    Set<Id> ids = cartMap.keySet();
    fflib_SObjectUnitOfWork uow = getUnitOfWork();
    List<Product2> productToUpdate = ProductSelector.newInstance()
      .selectByIds(new List<Id>(ids));

    Decimal totalPrice = 0;
    for (Product2 product : productToUpdate) {
      product.QuantityAvailable__c =
        product.QuantityAvailable__c - cartMap.get(product.Id);
      totalPrice += cartMap.get(product.Id) * product.PricePerUnit__c;
    }
    uow.registerDirty(productToUpdate);

    PurchaseOrder__c productOrder = new PurchaseOrder__c(
      OrderPrice__c = totalPrice,
      OrderStatus__c = 'Pending'
    );
    uow.registerNew(productOrder);

    for (Id productId : cartMap.keySet()) {
      PurchaseOrderLineItems__c lineItem = new PurchaseOrderLineItems__c(
        Product__c = productId,
        quantity__c = cartMap.get(productId)
      );
      uow.registerNew(
        lineItem,
        PurchaseOrderLineItems__c.PurchaseOrder__c,
        productOrder
      );
    }
    uow.commitWork();

    return productOrder.Id;
  }

  private static fflib_SObjectUnitOfWork getUnitOfWork() {
    fflib_SObjectUnitOfWork uow = new fflib_SObjectUnitOfWork(
      new List<Schema.SObjectType>{
        Product2.SObjectType,
        PurchaseOrder__c.SObjectType,
        PurchaseOrderLineItems__c.SObjectType
      }
    );
    return uow;
  }
}